# Generated by Django 2.2.4 on 2019-08-29 14:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WhatToDo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 14, 7, 22, 764660, tzinfo=utc)),
        ),
    ]
