# Generated by Django 2.2.4 on 2019-08-28 12:04

import WhatToDo.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WhatToDo', '0003_auto_20190827_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='TicketPrice1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, validators=[WhatToDo.validators.check_negative_number]),
        ),
        migrations.AlterField(
            model_name='event',
            name='TicketPrice2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, validators=[WhatToDo.validators.check_negative_number]),
        ),
        migrations.AlterField(
            model_name='event',
            name='TicketPrice3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, validators=[WhatToDo.validators.check_negative_number]),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='WhatToDo.Venue'),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 28, 12, 4, 52, 100404, tzinfo=utc)),
        ),
    ]
