# Generated by Django 2.2.4 on 2019-09-06 10:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WhatToDo', '0003_auto_20190905_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 6, 10, 22, 18, 31406, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'General'), (0, 'Friend')], default=1),
        ),
    ]
