# Generated by Django 2.2.4 on 2019-08-28 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WhatToDo', '0004_auto_20190828_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='endDate',
            field=models.DateTimeField(verbose_name='End Date and Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lastModified',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateTimeField(verbose_name='Start Date and Time'),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 28, 14, 37, 54, 308702, tzinfo=utc)),
        ),
    ]
