# Generated by Django 2.2.4 on 2019-09-06 12:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WhatToDo', '0004_auto_20190906_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 6, 12, 41, 8, 305137, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.IntegerField(choices=[(0, 'Friends'), (1, 'Request'), (2, 'Blocked')], default=1),
        ),
    ]
