# Generated by Django 2.2.4 on 2019-09-13 11:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WhatToDo', '0004_auto_20190913_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, default='events/default_events.jpg', null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 13, 11, 20, 5, 977255, tzinfo=utc)),
        ),
    ]
