# Generated by Django 2.2.4 on 2019-08-28 15:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WhatToDo', '0005_auto_20190828_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 28, 15, 16, 35, 551512, tzinfo=utc)),
        ),
    ]
