# Generated by Django 2.2.4 on 2019-09-06 13:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WhatToDo', '0005_auto_20190906_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 6, 13, 8, 5, 786055, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationships',
            field=models.ManyToManyField(related_name='related_to', through='WhatToDo.Relationship', to='WhatToDo.Profile'),
        ),
    ]
