# Generated by Django 2.2.4 on 2019-09-08 09:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WhatToDo', '0006_auto_20190906_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 8, 9, 21, 38, 863811, tzinfo=utc)),
        ),
    ]
