# Generated by Django 2.2.4 on 2019-09-27 13:54

import WhatToDo.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WhatToDo', '0006_auto_20190923_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='TicketPrice1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, validators=[WhatToDo.validators.check_negative_number], verbose_name='Lowest Ticket Price'),
        ),
        migrations.AlterField(
            model_name='event',
            name='TicketPrice2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, validators=[WhatToDo.validators.check_negative_number], verbose_name='Middle Ticket Price'),
        ),
        migrations.AlterField(
            model_name='event',
            name='TicketPrice3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, validators=[WhatToDo.validators.check_negative_number], verbose_name='Highest Ticket Price'),
        ),
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, default='default_events.jpg', null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WhatToDo.Venue'),
        ),
    ]
