# Generated by Django 2.2.4 on 2019-09-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhatToDo', '0006_auto_20190901_1941'),
        ('WhatToDo', '0007_auto_20190908_0921'),
    ]

    operations = [
    ]
