# Generated by Django 2.2.4 on 2019-10-15 19:09

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WhatToDo', '0012_auto_20191015_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_medium',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='profile/avatar.jpg', null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_small',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
